name: Validate Json

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build matrix"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout `sail-riscv` repo
        uses: actions/checkout@v3
        with:
          repository: ThinkOpenly/sail-riscv

      - name: Download Sail artifact
        uses: actions/download-artifact@v3
        with:
          name: sail-artifact

      - name: Make Sail executable
        run: |
          chmod +x sail
          sudo mv sail /usr/local/bin/sail

      - name: Generate json
        run: |
          sail --version
          make check-json
